include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_VENDOR "Vladimir")
set(CPACK_PACKAGE_CONTACT "123@mail.ru")
set(CPACK_PACKAGE_VERSION_MAJOR ${SOLVER_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${SOLVER_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${SOLVER_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${SOLVER_VERSION_TWEAK})
set(CPACK_PACKAGE_VERSION ${SOLVER_VERSION})
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

# Настройки для Linux (DEB/RPM)
set(CPACK_DEBIAN_PACKAGE_NAME "solver-app")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Your Name")
set(CPACK_DEBIAN_FILE_NAME "solver_${SOLVER_VERSION}_amd64.deb")

set(CPACK_RPM_PACKAGE_NAME "solver-app")
set(CPACK_RPM_PACKAGE_RELEASE 1)
set(CPACK_RPM_FILE_NAME "solver-${SOLVER_VERSION}-1.x86_64.rpm")

# Настройки для Windows (WIX)
set(CPACK_WIX_PRODUCT_GUID "5f048a0c-04cc-470d-9910-5b3357ab7f60") 
set(CPACK_WIX_UPGRADE_GUID "1bb927df-d973-44d7-b068-2cd917b7599d") 
set(CPACK_WIX_PRODUCT_ICON "${CMAKE_CURRENT_SOURCE_DIR}/assets/icon.ico")

# Настройки для macOS (DragNDrop)
set(CPACK_DMG_VOLUME_NAME "Solver Application")
set(CPACK_DMG_FORMAT "UDBZ")

include(CPack)
